apiVersion: v1
kind: Service
metadata:
  name: {{ include "iwd-demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iwd-demo.name" . }}
    helm.sh/chart: {{ include "iwd-demo.chart" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "iwd-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

