name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.0.0'

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t devops0819/iwd-demo .
          docker push devops0819/iwd-demo

      - name: Set GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: echo "machine github.com login $GH_TOKEN" > ~/.netrc

      - name: Update Helm Chart
        run: |
          sed -i "s/tag: latest/tag: ${{ github.run_number }}/" helm/iwd-demo/values.yaml
          helm dependency update helm/iwd-demo
          helm package helm/iwd-demo -d helm
          helm repo add my-charts https://my-charts-repo
          helm repo update
          helm push helm/iwd-demo my-charts --force

      - name: Deploy using Argo Rollouts
        run: |
          curl -sLO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
          chmod +x ./kubectl-argo-rollouts-linux-amd64
          sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
          kubectl argo rollouts set image iwd-demo iwd-demo=devops0819/iwd-demo:${{ github.run_number }}
